Исправить nginx и монтирование дополнительного диска

diff --git a/hw-01/cloud-init.tpl.yaml b/hw-01/cloud-init.tpl.yaml
--- a/hw-01/cloud-init.tpl.yaml
+++ b/hw-01/cloud-init.tpl.yaml
@@ -25,7 +25,7 @@ write_files:
           index index.html;
 
           location / {
-              try_files $uri $uri/ =404;
+              try_files \$uri \$uri/ =404;
           }
       }
 
@@ -46,13 +46,21 @@ write_files:
 
 runcmd:
   - |
-    if ! blkid /dev/disk/by-id/virtio-data-disk; then
-      mkfs.ext4 /dev/disk/by-id/virtio-data-disk
+    DISK="/dev/vdb"
+
+    if ! blkid "$DISK"; then
+      mkfs.ext4 "$DISK"
     fi
-  - mkdir -p /mnt/data
-  - |
-    UUID=$(blkid -s UUID -o value /dev/disk/by-id/virtio-data-disk)
-    grep -q "$UUID" /etc/fstab || echo "UUID=$UUID /mnt/data ext4 defaults,nofail 0 2" >> /etc/fstab
-  - mount -a
+
+    mkdir -p /mnt/data
+
+    UUID=$(blkid -s UUID -o value "$DISK")
+
+    if ! grep -q "$UUID" /etc/fstab; then
+      echo "UUID=$UUID /mnt/data ext4 defaults,nofail 0 2" >> /etc/fstab
+    fi
+
+    mount -a
+
   - systemctl enable nginx
   - systemctl restart nginx
