Исправить форматирование и монтирование дополнительного диска

diff --git a/hw-01/cloud-init.tpl.yaml b/hw-01/cloud-init.tpl.yaml
--- a/hw-01/cloud-init.tpl.yaml
+++ b/hw-01/cloud-init.tpl.yaml
@@ -46,18 +46,15 @@ write_files:
 
 runcmd:
   - |
-    DISK="/dev/vdb"
 
-    if ! blkid "$DISK"; then
-      mkfs.ext4 "$DISK"
+    if ! blkid /dev/vdb; then
+      mkfs.ext4 /dev/vdb
     fi
 
     mkdir -p /mnt/data
 
-    UUID=$(blkid -s UUID -o value "$DISK")
-
-    if ! grep -q "$UUID" /etc/fstab; then
-      echo "UUID=$UUID /mnt/data ext4 defaults,nofail 0 2" >> /etc/fstab
+    if ! grep -q "$(blkid -s UUID -o value /dev/vdb)" /etc/fstab; then
+      echo "UUID=$(blkid -s UUID -o value /dev/vdb) /mnt/data ext4 defaults,nofail 0 2" >> /etc/fstab
     fi
 
     mount -a
